version: '2'
services:
  fluentd:
    build: ./fluentd
    container_name: fluentd_demo
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./fluentd/plugins:/fluentd/plugins
    depends_on:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    logging:
        driver: "json-file"
        options:
            max-size: 100m
            max-file: "5"
    restart: always


  elasticsearch:
    image: elasticsearch:6.6.2
    container_name: elasticsearch_demo
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "cluster.name=docker-cluster"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    volumes:
      - ./data:/usr/share/elasticsearch/data


  kibana:
    image: kibana:6.6.2
    container_name: kibana_demo
    depends_on: 
      - "elasticsearch"
    ports:
      - "5601:5601"
    restart: always

  # nginx:
  #   image: nginx
  #   links:
  #     - "fluentd"
  #   depends_on: 
  #     - "fluentd"
  #   ports:
  #     - "80:80"
  #   logging:
  #     driver: "fluentd"
  #     options:
  #       fluentd-address: localhost:24224
  #       tag: nginx
  #   restart: always

  demo:
    build: ./example
    container_name: demo
    depends_on:
      - "fluentd"
    logging:
      driver: "fluentd"
      options:
        tag: moblab.{{.Name}}



  httpd:
    image: httpd
    container_name: httpd
    depends_on:
      - "fluentd"
    ports:
      - "8083:80"
    logging:
      driver: "fluentd"
      options:
        tag: moblab.{{.Name}}

