apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: fluentd
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
      - image: fluentd:dev
        name: fluentd
        ports:
        - containerPort: 5601
          name: fluentd
        volumeMounts:
          - mountPath: /fluentd/etc
            name: config-data
          - mountPath: /fluentd/plugins
            name: plugin-data    
          - mountPath: /var/log
            name: varlog 
          - mountPath: /var/lib/docker/containers
            name: varlibdockercontainers         
      volumes:
        - name: config-data        
          hostPath:
            path: /Users/lisheng/workspace/fluentd-demo/fluentd/conf
        - name: plugin-data        
          hostPath:
            path: /Users/lisheng/workspace/fluentd-demo/fluentd/plugins
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
